name: pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    name: action-pretty-yarrrml2rml
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: commit trigger
        id: 'commit_trigger'
        run: |

          case "${{ github.event.head_commit.message }}" in
              *yarrrml2rml* ) echo "::set-output name=trigger::true";;
              * ) echo "::set-output name=trigger::false";;
          esac

      - name: installing yarrrml2rml
        run: |
          if ${{ steps.commit_trigger.outputs.trigger }}
          then
            python3 -m pip install pretty-yarrrml2rml
          fi

      - name: action-yarrrml2rml
        uses: ./
        id: 'action-yarrrml2rml'

      - name: running morph-kgc
        run: |
          if ${{ steps.action-morphkgc.outputs.run }} && ${{ steps.commit_trigger.outputs.trigger }}
          then
            python3 -m pretty_yarrrml2rml -i path_to_input_yarrrml.yml -o path_to_output_rml.rml
            rm -r ./pretty_yarrrml2rml-exec

            git config --global user.name 'github-actions[bot]'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add .
            set +e
            git status | grep "nothing to commit, working tree clean"
            if [ $? -eq 0 ]; then set -e; echo "INFO: No changes since last run"; else set -e; \
              git commit -m "morph-kgc result for ${{ github.actor }} - ${{ github.event.number }}" --allow-empty; git push --force; fi
          fi
